#define DRIVE_LEFT_MOTORS {-12, -19, -16}
#define DRIVE_RIGHT_MOTORS {13, 18, 11}
#define DRIVE_IMU 9
#define DRIVE_WHEEL_DIAMETER 4.0
#define DRIVE_MOTOR_CARTRIGE 200
#define DRIVE_GEAR_RATIO 1.0
#define DRIVE_GPS_PORTS {6, 3}
#define DRIVE_GPS_X_OFFSETS {.13, .22}
#define DRIVE_GPS_Y_OFFSETS {.13, .05}
#define DRIVE_GPS_YAW_OFFSETS {90, 0}
#define GRABBER_MOTOR_PORT 10
#define GRABBER_PISTON1 'd'
#define GRABBER_MOTOR_GEARSET MOTOR_GEARSET_18
#define GRABBER_MOTOR_REVERSED true
#define GRABBER_SENSOR_PORT 'c'
#define HOARDER_MOTOR_PORT 8
#define HOARDER_MOTOR_GEARSET MOTOR_GEARSET_36
#define HOARDER_PISTON1 'a'
#define HOARDER_PISTON2 'b'
#define HOARDER_MOTOR_REVERSED true
#define LIFT_MOTOR_PORT 14
#define LIFT_MOTOR_GEARSET MOTOR_GEARSET_36
#define LIFT_MOTOR_REVERSED true
#define LIFT_UP_DEGREES 510
#define LIFT_PLACE_DEGREES 310
#define LIFT_UP2_DEGREES 800
#define LIFT_PULL_DEGREES 200
#define INTAKE_MOTOR_PORT 17
#define INTAKE_MOTOR_GEARSET MOTOR_GEARSET_18
#define INTAKE_MOTOR_REVERSED false